name: recriacao_devoraquiz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.17
  firebase_database: ^9.0.15
  firebase_core: ^1.17.1
  google_fonts: ^3.0.1
  scoped: ^3.1.1
  scoped_model: ^1.1.0

  # Google Sign in
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.3

  # Google Icon
  font_awesome_flutter: ^9.2.0

  # State management
  provider: ^6.0.2

  # Audio player
  audioplayers: ^0.20.1

  websafe_svg: ^2.1.1

  get: ^4.6.1

  animations: ^2.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"
  
  

flutter_icons: 
  image_path: "assets/images/launcherIcon.png"
  android: true
  ios: true


flutter:

  assets:
    - assets/audio/welcomeAudio.mp3
    - assets/audio/pop_sound.mp3
    - assets/icons/

  uses-material-design: true
